-- Replace sample data with complete MVP stories

-- Delete existing sample data
DELETE FROM story_scenes WHERE story_id IN (
  SELECT id FROM stories WHERE title IN ('The Dragon Adventure', 'Space Journey', 'Underwater Mystery')
);
DELETE FROM stories WHERE title IN ('The Dragon Adventure', 'Space Journey', 'Underwater Mystery');

-- Insert MVP stories with auto-generated UUIDs
INSERT INTO stories (title, description, status, author_id) VALUES
('The Magical Space Journey', 'Embark on a magical journey through space with a friendly alien named Cosmo. Visit distant planets, meet wonderful creatures, and discover the wonders of the cosmos.', 'published', NULL),
('The Friendly Dragon', 'Meet a friendly dragon named Emerald and embark on wonderful adventures together. Discover hidden treasures, explore magical places, and learn about true friendship.', 'published', NULL),
('The Underwater Adventure', 'Dive into an amazing underwater world with a friendly dolphin named Pearl. Explore coral reefs, meet sea creatures, and discover the magic beneath the waves.', 'published', NULL);

-- Insert Space Journey scenes
INSERT INTO story_scenes (story_id, scene_order, title, content, choices, background_image_url) VALUES
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 1, 'A Magical Visitor', '{{childName}} was stargazing in their backyard when something extraordinary appeared! A shimmering, silver rocket ship landed softly in the garden, decorated with twinkling lights that looked like captured stars. Out popped a friendly alien named Cosmo, who had big, kind eyes and skin that sparkled like the night sky. ''Greetings, {{childName}}!'' Cosmo said with excitement. ''I''m on a mission to visit all the most beautiful places in the galaxy. Would you like to be my co-pilot and see the wonders of space?''', '[{"label": "Accept the space adventure", "next_scene_id": 2}, {"label": "Ask Cosmo about their home planet first", "next_scene_id": 3}]'::jsonb, 'castle.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 2, 'Preparing for Launch', '''Wonderful!'' exclaimed Cosmo. ''But first, every good space explorer needs supplies!'' Together, they packed the most important things for a space journey—{{childName}}''s favorite snacks, a cozy blanket for stargazing, and a special notebook to draw all the amazing things they would see. Cosmo showed {{childName}} the rocket''s control panel, with buttons that glowed different colors. ''The blue button starts the gentle engines, the green button plays space music, and the gold button... well, that one''s a surprise!'' Cosmo winked.', '[{"label": "Press the blue button to blast off", "next_scene_id": 4}, {"label": "Press the green button for space music first", "next_scene_id": 5}]'::jsonb, 'meadow.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 3, 'Learning About Stellaria', 'Cosmo''s eyes twinkled as they described their wonderful home planet. ''It''s called Stellaria, and it''s covered in crystal forests that sing when the wind blows through them! We have rivers made of liquid starlight, and flowers that bloom only under the light of three purple moons. But the best part is that everyone there believes in friendship and helping others—that''s why I travel the galaxy, making friends like you!'' {{childName}} thought Stellaria sounded like the most magical place imaginable.', '[{"label": "Ask to visit Stellaria", "next_scene_id": 6}, {"label": "Suggest exploring other planets first", "next_scene_id": 2}]'::jsonb, 'forest.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 4, 'Blasting Off!', '3... 2... 1... WHOOSH! The rocket lifted off so gently it felt like floating on a cloud. Through the clear dome window, {{childName}} watched Earth get smaller and smaller until it looked like a beautiful blue marble decorated with swirling white clouds. ''There''s your home!'' Cosmo pointed. ''Isn''t it magnificent?'' All around them, stars twinkled like friendly diamonds, and in the distance, they could see the moon waving hello with its gentle, silvery light.', '[{"label": "Wave back at the moon", "next_scene_id": 7}, {"label": "Ask to visit the colorful planet ahead", "next_scene_id": 8}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 5, 'The Music of Space', 'The most wonderful music filled the rocket ship—it sounded like wind chimes mixed with gentle ocean waves and the sweetest bird songs! ''This is the music of the cosmos,'' Cosmo explained. ''Every planet, every star, every comet has its own special song. When you put them all together, you get the symphony of space!'' {{childName}} discovered they could conduct the music by moving their hands, making the melodies dance and swirl around the rocket ship.', '[{"label": "Compose your own space song", "next_scene_id": 7}, {"label": "Ask to hear Earth''s song", "next_scene_id": 4}]'::jsonb, 'meadow.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 6, 'Visiting Stellaria', 'Stellaria was even more beautiful than Cosmo had described! The crystal trees chimed like bells in harmonious melodies as {{childName}} and Cosmo walked through the singing forest. The liquid starlight rivers sparkled with every color imaginable, and friendly Stellarians—who looked like Cosmo but in different beautiful colors—came out to welcome their Earth visitor. They gifted {{childName}} a small crystal that would always play the music of Stellaria, no matter how far from home they traveled.', '[{"label": "Thank the Stellarians and explore more planets", "next_scene_id": 9}, {"label": "Ask to learn a Stellarian song", "next_scene_id": 10}]'::jsonb, 'forest.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 7, 'Meeting the Moon Rabbit', 'The moon was delighted to have visitors! As they flew closer, {{childName}} could see that the moon''s surface was covered in the most beautiful silver sand that sparkled like glitter. A friendly moon rabbit hopped out to greet them, offering moon cookies that tasted like vanilla and starlight. ''The Earth looks so peaceful from here,'' the moon rabbit said. ''I love watching over all the children while they sleep, making sure their dreams are filled with wonder.'' {{childName}} felt honored to meet such a caring guardian.', '[{"label": "Promise to wave at the moon every night", "next_scene_id": 9}, {"label": "Ask the moon rabbit about space dreams", "next_scene_id": 10}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 8, 'Rainbow World', 'The colorful planet was called Rainbow World, and it was incredible! Every part of the planet was a different color—purple mountains, orange rivers, green clouds, and yellow trees that grew rainbow fruit. The friendly Rainbow World inhabitants were living colors themselves, changing hues as their moods shifted. They taught {{childName}} and Cosmo how to paint with liquid rainbows, creating pictures that shimmered and moved like living art. ''Colors are the language of joy!'' explained a cheerful inhabitant who was currently bright turquoise.', '[{"label": "Create a rainbow painting of Earth", "next_scene_id": 9}, {"label": "Ask to take rainbow paint back to Earth", "next_scene_id": 10}]'::jsonb, 'meadow.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 9, 'The Journey Ends', 'As their amazing space journey came to an end, {{childName}} and Cosmo sat on the rocket''s observation deck, watching the beautiful dance of stars and planets. ''Thank you for being the best co-pilot in the galaxy,'' Cosmo said warmly. ''You''ve helped me discover that the most wonderful thing about space isn''t the places you visit—it''s the friends you make along the way.'' As Earth came into view, {{childName}} felt grateful for the adventure and excited to share the magic of space with everyone back home.', '[{"label": "Plan another space adventure for next week", "next_scene_id": 11}, {"label": "Ask Cosmo to meet your family", "next_scene_id": 12}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 10, 'A Perfect Ending', 'What a perfect way to end their space adventure! {{childName}} learned that the secret to space travel isn''t just about the amazing technology or the incredible sights—it''s about approaching everything with wonder, kindness, and an open heart. As they landed gently back in the garden, Cosmo gave {{childName}} a special space explorer badge that glowed softly in the dark. ''This will remind you that adventure is always waiting, whether it''s in the farthest reaches of space or right in your own backyard,'' Cosmo said with a smile.', '[{"label": "Promise to always look up at the stars and remember", "next_scene_id": 11}, {"label": "Invite Cosmo to stay and explore Earth", "next_scene_id": 12}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 11, 'Looking to the Stars', 'Every night after their incredible adventure, {{childName}} would look up at the star-filled sky and wave at their friend Cosmo, who had promised to return soon for another magical journey. The crystal from Stellaria would play its gentle music, the moon rabbit would wink from their lunar home, and {{childName}} would fall asleep planning all the wonderful places they would explore next. Sometimes the greatest adventures begin when you''re brave enough to say yes to the unknown.', '[]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Magical Space Journey'), 12, 'Cosmo Stays on Earth', 'Cosmo was thrilled to stay and learn about Earth! Together, they explored {{childName}}''s garden, discovering that Earth had its own special magic—flowers that smelled like happiness, butterflies that painted the air with color as they flew, and the most beautiful sunrise that painted the sky in shades Cosmo had never seen on any other planet. ''Every world has its own special wonder,'' Cosmo said as they watched the stars appear one by one. ''And the most wonderful thing of all is sharing these discoveries with a true friend.''', '[]'::jsonb, 'sunset.svg');

-- Insert Dragon Adventure scenes
INSERT INTO story_scenes (story_id, scene_order, title, content, choices, background_image_url) VALUES
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 1, 'A Dragon Discovery', 'One bright morning, {{childName}} was exploring the hills near an ancient castle when something extraordinary happened! Behind a tall tower, they spotted a magnificent dragon with shimmering emerald scales. But this dragon wasn''t scary at all—it had kind, twinkling eyes and was sitting quietly, looking a bit lonely. The dragon noticed {{childName}} and tilted its head curiously.', '[{"label": "Wave hello to the dragon", "next_scene_id": 2}, {"label": "Walk closer to the moat", "next_scene_id": 3}]'::jsonb, 'castle.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 2, 'Making Friends', 'The dragon''s face lit up with joy! It waved back with one giant wing and spoke in a gentle, rumbly voice: ''Hello there, {{childName}}! I''m Emerald. I''ve been waiting so long for a friend to visit me.'' The dragon''s eyes sparkled with happiness. ''Would you like to see my favorite meadow? I can show you where the most beautiful wildflowers grow, and we could fly there together—I promise to fly very gently!''', '[{"label": "Accept the dragon ride", "next_scene_id": 4}, {"label": "Ask to walk to the meadow instead", "next_scene_id": 5}]'::jsonb, 'meadow.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 3, 'The Magic Pebbles', 'As {{childName}} walked along the castle''s moat, they discovered something magical! The water was crystal clear, and at the bottom were hundreds of smooth pebbles that glowed with an inner light—some blue like sapphires, others golden like sunshine. Just then, the dragon appeared beside the moat. ''Oh, you found my treasure pebbles!'' Emerald said warmly. ''I''ve been collecting them for years. Each one holds a happy memory. Would you like to choose one to keep?''', '[{"label": "Choose a blue glowing pebble", "next_scene_id": 6}, {"label": "Choose a golden pebble", "next_scene_id": 7}]'::jsonb, 'forest.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 4, 'The Dragon Flight', 'What a wonderful ride! Emerald flew so smoothly that it felt like floating on a gentle breeze. The meadow below was bursting with rainbow-colored flowers that danced in the wind. As they landed softly, Emerald showed {{childName}} how to make flower crowns, and they spent the afternoon picking daisies, roses, and lavender. ''You''re the best friend I''ve ever had,'' Emerald said, placing a flower crown on {{childName}}''s head.', '[{"label": "Make a flower crown for Emerald too", "next_scene_id": 8}, {"label": "Ask Emerald to tell a story", "next_scene_id": 9}]'::jsonb, 'meadow.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 5, 'Walking Together', 'Together, {{childName}} and Emerald walked through the countryside, chatting like old friends. Emerald told wonderful stories about the clouds and pointed out hidden animal homes along the way. When they reached the meadow, Emerald used gentle puffs of warm (not hot!) dragon breath to help all the flowers bloom extra bright. ''Walking with a friend makes every journey special,'' Emerald said with a happy sigh.', '[{"label": "Pick flowers together", "next_scene_id": 8}, {"label": "Sit and watch the clouds", "next_scene_id": 9}]'::jsonb, 'meadow.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 6, 'The Friendship Pebble', '{{childName}} chose a beautiful blue pebble that felt warm and comforting in their hand. Emerald explained that this was a ''friendship pebble''—it would always remind them of their new dragon friend. As the sun began to set, painting the sky in magnificent purples and golds, Emerald and {{childName}} sat by the castle, sharing stories and laughing together. ''This has been the most wonderful day,'' Emerald said. ''Promise you''ll come visit again soon?''', '[{"label": "Promise to visit every week", "next_scene_id": 10}, {"label": "Invite Emerald to visit your home too", "next_scene_id": 11}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 7, 'The Courage Pebble', 'The golden pebble {{childName}} chose began to glow even brighter in their palm! ''Ah,'' said Emerald with delight, ''you''ve picked a courage pebble! This one will remind you that you''re brave enough to make new friends and try new adventures.'' As the golden sunset painted everything in warm light, they sat together sharing their favorite memories. ''You helped me remember that the best treasures aren''t things—they''re friendships,'' Emerald said gratefully.', '[{"label": "Give Emerald a thank-you hug", "next_scene_id": 10}, {"label": "Ask if you can be pen pals", "next_scene_id": 11}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 8, 'Flower Crowns for Everyone', 'With gentle fingers, {{childName}} wove a magnificent flower crown fit for a dragon, with extra-long daisy chains that draped beautifully around Emerald''s neck. ''I feel like the most elegant dragon in the whole world!'' Emerald laughed, striking a royal pose that made {{childName}} giggle. As the sun set, they danced in the meadow, flower crowns sparkling in the golden light. It was the perfect end to a perfect day of friendship.', '[{"label": "Plan another adventure for tomorrow", "next_scene_id": 10}, {"label": "Exchange friendship bracelets", "next_scene_id": 11}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 9, 'Cloud Watching', 'Lying on their backs in the soft grass, {{childName}} and Emerald watched the clouds drift by, taking turns pointing out shapes—a sailing ship, a giant ice cream cone, a family of rabbits! Emerald told wonderful tales about cloud dragons who painted rainbows across the sky. As the first stars began to twinkle, {{childName}} realized they had made not just a friend, but a friend who would fill their life with magic and wonder.', '[{"label": "Make a wish on the first star together", "next_scene_id": 10}, {"label": "Promise to meet here every sunset", "next_scene_id": 11}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 10, 'A Promise of Adventures', 'As the stars twinkled overhead, {{childName}} and Emerald made a wonderful promise to meet every week for new adventures. ''We could explore the Whispering Woods, or visit the Crystal Caves, or maybe even meet my cousin dragon who lives by the sea!'' Emerald said excitedly. {{childName}} hugged their new friend goodbye, knowing that this was just the beginning of many magical adventures. Sometimes the most wonderful friendships begin with a simple wave hello.', '[]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Friendly Dragon'), 11, 'Inviting Emerald Home', 'What a brilliant idea! Emerald was thrilled to be invited to visit {{childName}}''s world too. ''I could help in your garden, and give the best piggyback rides, and maybe teach your family how to roast marshmallows with perfectly warm dragon breath!'' they planned together. As they said goodbye with a gentle dragon hug, {{childName}} knew they had found a friend who would bring magic and joy wherever they went. True friendship makes the whole world brighter!', '[]'::jsonb, 'sunset.svg');

-- Insert Underwater Adventure scenes
INSERT INTO story_scenes (story_id, scene_order, title, content, choices, background_image_url) VALUES
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 1, 'A Dolphin Friend', '{{childName}} was building sandcastles on a beautiful beach when something amazing happened! A shimmering dolphin poked its head above the waves and clicked a cheerful hello. The dolphin''s name was Pearl, and she had the most intelligent, sparkling eyes. ''I''ve been watching you build that wonderful castle,'' Pearl said in a voice like tinkling bells. ''Would you like to see the magical world beneath the waves? I know the most incredible places down there!''', '[{"label": "Dive underwater with Pearl", "next_scene_id": 2}, {"label": "Show Pearl your sandcastle first", "next_scene_id": 3}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 2, 'The Coral Reef', 'Pearl touched {{childName}} with her fin, and suddenly they could breathe underwater like a fish! Down, down, down they swam, past schools of rainbow-colored fish and swaying seaweed forests. ''Look!'' Pearl pointed with her fin. Ahead was the most beautiful coral reef {{childName}} had ever imagined—pink and purple corals shaped like flowers, with tiny fish darting in and out like living jewels. A wise old sea turtle named Shelly swam up to greet them. ''Welcome to our underwater garden!'' Shelly said warmly.', '[{"label": "Swim through the coral garden", "next_scene_id": 4}, {"label": "Ask Shelly about the sea creatures", "next_scene_id": 5}]'::jsonb, 'meadow.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 3, 'The Sandcastle', '{{childName}} proudly showed Pearl their magnificent sandcastle, complete with seashell windows and a moat filled with pretty pebbles. Pearl was delighted! ''This is wonderful!'' she exclaimed. ''You know, we have something similar under the sea—would you like to see the coral castles where my fish friends live? They''re made of living coral that grows in all the colors of the rainbow!'' Pearl''s excitement was contagious, and {{childName}} couldn''t wait to explore.', '[{"label": "Dive down to see the coral castles", "next_scene_id": 2}, {"label": "Ask Pearl to help improve your sandcastle first", "next_scene_id": 6}]'::jsonb, 'castle.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 4, 'Underwater Games', 'Swimming through the coral garden was like floating through a fairy tale! Everywhere {{childName}} looked, there were new wonders—anemones that waved hello like underwater flowers, hermit crabs wearing shell hats, and seahorses that danced in pairs. A friendly octopus named Inky showed them how to play underwater tag, using all eight arms to be ''it'' at once! ''The ocean is full of friends if you know how to look,'' Pearl said as they played together in the dancing seaweed.', '[{"label": "Play more games with the sea creatures", "next_scene_id": 7}, {"label": "Explore the deeper waters with Pearl", "next_scene_id": 8}]'::jsonb, 'forest.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 5, 'Learning About Sea Life', 'Shelly the sea turtle was full of wonderful stories! She told {{childName}} about the singing whales who lived in the deep waters, the dolphins who surfed on waves, and the tiny seahorses who held hands so they wouldn''t get lost in the currents. ''Every creature in the ocean has a special job,'' Shelly explained. ''The cleaner fish help keep everyone healthy, the coral provides homes for thousands of fish families, and we turtles help plant new seagrass meadows by carrying seeds on our shells!''', '[{"label": "Ask to help plant seagrass", "next_scene_id": 7}, {"label": "Request to meet the singing whales", "next_scene_id": 8}]'::jsonb, 'forest.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 6, 'Improving the Sandcastle', 'Pearl used her powerful tail to splash just the right amount of water to make {{childName}}''s sandcastle even more magnificent! Together they decorated it with the most beautiful shells, smooth sea glass, and pieces of coral that had washed up on the beach. Other sea creatures poked their heads above the waves to admire their work. ''This is the most beautiful sandcastle in the whole ocean!'' declared a cheerful sea gull. {{childName}} felt so proud of their creation.', '[{"label": "Dive underwater to see Pearl''s home", "next_scene_id": 2}, {"label": "Invite all the sea creatures for a sandcastle party", "next_scene_id": 9}]'::jsonb, 'castle.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 7, 'Planting Seagrass', 'What a wonderful way to help the ocean! {{childName}} and Pearl worked together with Shelly to plant new seagrass seeds in a sunny underwater meadow. The baby fish came to watch, and even helped by creating tiny whirlpools with their fins to help the seeds settle into the sand. ''In a few months, this will be a beautiful underwater meadow where young fish can play and hide,'' Shelly explained. {{childName}} felt happy knowing they had helped create a home for sea creatures.', '[{"label": "Promise to come back and see how it grows", "next_scene_id": 10}, {"label": "Ask Pearl to show you her favorite hiding spot", "next_scene_id": 11}]'::jsonb, 'meadow.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 8, 'Meeting the Whales', 'In the deeper, quieter waters, {{childName}} and Pearl encountered something truly magical—a family of whales swimming gracefully through the blue depths. The mother whale sang the most beautiful song, like a melody from a dream. ''She''s singing about the wonders of the ocean and welcoming you to our underwater world,'' Pearl translated. The baby whale came closer and gently touched {{childName}} with its fin, as if saying thank you for visiting their home.', '[{"label": "Try to sing back to the whales", "next_scene_id": 10}, {"label": "Ask Pearl to teach you whale songs", "next_scene_id": 11}]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 9, 'Sandcastle Party', 'What a delightful party! Sea creatures from all over came to admire the beautiful sandcastle. Pelicans brought seaweed streamers, crabs brought shiny shells for decorations, and Pearl organized underwater races around the castle moat. Even a majestic sea turtle brought a gift—a special piece of sea glass that glowed blue-green in the sunlight. ''This has been the best day ever!'' laughed a little hermit crab as they all celebrated together.', '[{"label": "Thank everyone and dive underwater for more adventures", "next_scene_id": 10}, {"label": "Ask if they can have parties like this every week", "next_scene_id": 11}]'::jsonb, 'castle.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 10, 'Saying Goodbye', 'As the sun began to set, painting the ocean in shades of gold and pink, {{childName}} and Pearl floated on the gentle waves, watching the first stars appear. ''Thank you for showing me the wonders of your underwater world,'' {{childName}} said. Pearl smiled her dolphin smile. ''And thank you for reminding me how magical it is to see the ocean through new eyes. The sea is always here when you want to explore!'' They promised to meet again soon for more underwater adventures.', '[]'::jsonb, 'sunset.svg'),
((SELECT id FROM stories WHERE title = 'The Underwater Adventure'), 11, 'Learning Whale Songs', 'What a wonderful idea! Pearl taught {{childName}} a simple whale song—a gentle humming melody that meant ''hello, friend'' in whale language. As they practiced together in the shallow waters, other dolphins came to join them, creating the most beautiful underwater choir. ''Now you can talk to any sea creature you meet,'' Pearl said proudly. {{childName}} realized they had not just learned about the ocean, but had become part of its magical family. The sea would always welcome them home.', '[]'::jsonb, 'sunset.svg');
